namespace: phoneshin
commonLabels:
  app: phoneshin-crawl
  env: prod
resources:
  - ../../base
patches:
  - path: cronjob.yaml
    target:
      kind: CronJob
      name: phoneshin-crawl-subsidy
images:
  - name: 'registry-harbor.phoneshin.com/phoneshin/crawl'
    newName: 'registry-harbor.phoneshin.com/phoneshin/crawl'
    newTag: 3394f96257f4c1b2f1c8aa7680a0254848f73aaa
