namespace: phoneshin
commonLabels:
  app: phoneshin-crawl
  env: prod
resources:
  - ../../base
patches:
  - path: cronjob.yaml
    target:
      kind: CronJob
      name: phoneshin-crawl-subsidy
images:
  - name: 'registry-harbor.phoneshin.com/phoneshin/crawl'
    newName: 'registry-harbor.phoneshin.com/phoneshin/crawl'
    newTag: d8b8903b282ebd10435c0d9bc1ba2972ed22089d
