namespace: phoneshin
commonLabels:
  app: phoneshin-crawl
  env: prod
resources:
  - ../../base
patches:
  - path: cronjob.yaml
    target:
      kind: CronJob
      name: phoneshin-crawl-subsidy
images:
  - name: 'registry-harbor.phoneshin.com/phoneshin/crawl'
    newName: 'registry-harbor.phoneshin.com/phoneshin/crawl'
    newTag: ca4908feb5bfc8213a2f112c2bd1549ff8f582c7
